stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository
build:
  stage: build
  image: maven:3.8.1-openjdk-11
  script:
    - mvn install -DskipTests
test:
  stage: test
  image: maven:3.8.1-openjdk-11
  services:
    - name: selenium/standalone-chrome
      alias: selenium
  script:
    - echo "Waiting for Selenium Grid to be ready..."
    - sleep 10  # Give some time for the Selenium container to start
    - curl -sSf http://selenium:4444/wd/hub/status || (echo "Selenium Grid is not reachable" && exit 1)
    - mvn test -DsuiteXmlFile=testng.xml
  artifacts:
    reports:
      junit: target/surefire-reports/testng-results.xml
    paths:
      - target/surefire-reports/

