stages:
  - test

variables:
  SELENIUM_SERVER_NAME: selenium-hub
  SELENIUM_SERVER_URL: http://${SELENIUM_SERVER_NAME}:4444
  DOCKER_HOST: tcp://docker:2375

services:
  - docker:20.10.16-dind

test:
  stage: test
  image: docker/compose:latest

  before_script:
    - docker-compose up -d selenium-hub chrome firefox edge
    - sleep 15  # Allow services to initialize
    - docker-compose run ping curl ${SELENIUM_SERVER_URL}/status
    - docker-compose exec chrome Xvfb :99 -screen 0 1920x1080x24 &
    - echo "Connect to the VNC server on localhost:5900 with password 'secret' to see the browser in GUI mode"
  script:
    - docker-compose run tests mvn clean test -Dchrome.options="--no-sandbox --disable-dev-shm-usage"
    - docker-compose logs chrome
  artifacts:
    when: always
    name: "report"
    paths:
      - target/surefire-reports/**
      - target/screenshots/**  # Include screenshots if applicable
    expire_in: 7 days
