### .gitlab-ci.yml
image: mcr.microsoft.com/windows/servercore:ltsc2022

stages:
  - build
  - test

variables:
  SELENIUM_SERVER_URL: http://selenium:4444/wd/hub
  RDP_PASSWORD: "P@ssword123"

before_script:
  - echo "Installing Docker CLI..."
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  - dockerd-entrypoint.sh &
  - sleep 20

build:
  stage: build
  script:
    - echo "Starting Windows Container with GUI..."
    - docker network create selenium-network
    - docker run -d --name selenium-hub --network=selenium-network -p 4444:4444 selenium/hub:latest
    - docker run -d --name chrome-node --network=selenium-network -e HUB_HOST=selenium-hub -p 5900:5900 selenium/node-chrome:latest
    - docker run -d --name windows-container --network=selenium-network --rm -p 3389:3389 mcr.microsoft.com/windows/servercore:ltsc2022
    - echo "Containers are now running."

test:
  stage: test
  script:
    - echo "Running Selenium Test Cases..."
    - docker exec -i windows-container powershell -Command "cd C:\\tests && mvn clean test"
    - echo "Test execution completed."
  artifacts:
    paths:
      - C:/tests/target/surefire-reports/