stages:
  - build
  - test

variables:
    SELENIUM_SERVER_URL: http://selenium:4444/wd/hub
    RDP_PASSWORD: "P@ssword123"

services:
  - docker:20.10.16-dind

build:
  stage: build
  script:
    - docker-compose up -d

run_tests:
  stage: test
  script:
    - docker exec -i windows-container powershell -Command "Start-Process 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'"
    - docker exec -i selenium-chrome /bin/sh -c "java -jar selenium-server-standalone.jar"
    - docker exec -i windows-container powershell -Command "cd C:\\tests && mvn clean test"

artifacts:
  paths:
    - test-output/
