stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2
  RDP_PASSWORD: "P@ssword123"

services:
  - docker:20.10.16-dind

build:
  stage: build
  script:
    - echo "Starting Docker Daemon..."
    - dockerd-entrypoint.sh &
    - sleep 20
    - echo "Starting Windows Container with GUI..."
    - docker run -d --name windows-container --rm -p 3389:3389 mcr.microsoft.com/windows/servercore:ltsc2022
    - sleep 30
  tags:
    - docker
  artifacts:
    paths:
      - target/

test:
  stage: test
  script:
    - echo "Installing Maven..."
    - apt-get update && apt-get install -y maven
    - echo "Running Selenium Test Cases..."
    - mvn clean test
  tags:
    - docker
  artifacts:
    paths:
      - target/surefire-reports/
      - target/screenshots/
  when: always
