test:
  stage: test
  image: maven:3.8.1-jdk-11-selenium
  services:
    - selenium/standalone-chrome
  script:
    - mvn test -DsuiteXmlFile=testng.xml
  artifacts:
    reports:
      junit: target/surefire-reports/testng-results.xml
    paths:
      - target/surefire-reports/