### docker-compose.yml
version: '3'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"
      - "5900:5900" # VNC port for GUI mode
    environment:
      - START_XVFB=false
    shm_size: '2gb'

  windows-container:
    image: mcr.microsoft.com/windows/servercore:ltsc2022
    container_name: windows-container
    ports:
      - "3389:3389" # RDP port
    environment:
      - ACCEPT_EULA=Y
    tty: true

networks:
  default:
    driver: bridge


