name: Run Tests

on:
  push:
    branches:
      - working
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:4.11.0-20230801
        ports:
          - 4444:4444

      chrome:
        image: selenium/node-chrome:4.11.0-20230801
        shm_size: 2gb
        depends_on:
          - selenium-hub
        environment:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

      firefox:
        image: selenium/node-firefox:4.11.0-20230801
        shm_size: 2gb
        depends_on:
          - selenium-hub
        environment:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 20

      - name: Set up Maven
        run: mvn -version

      - name: Run Tests
        run: |
          mvn clean test
        env:
          SELENIUM_SERVER_URL: http://selenium-hub:4444
