mage: maven:3.8.1-openjdk-11

services:
  - name: selenium/standalone-chrome:118.0
    alias: selenium

stages:
  - test

test:
  stage: test
  script:
    - echo "Updating package lists..."
    - apt-get update && apt-get install -y xvfb
    - echo "Starting virtual display..."
    - export DISPLAY=:99
    - Xvfb :99 -screen 0 1920x1080x24 &
    - sleep 10  # Wait for Selenium to start
    - echo "Running Selenium tests..."
    - mvn test -DsuiteXmlFile=testng.xml
  artifacts:
    reports:
      junit: target/surefire-reports/testng-results.xml
    paths:
      - target/surefire-reports/
